name = "Lax560851Proofs"
defaultTargets = ["Lax560851Proofs"]

[leanOptions]
autoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "db584cd6d46c92f209a44c0f1c829460d327499d"

[[require]]
name = "Lax560851"
path = "../concepts"

[[lean_lib]]
name = "Lax560851Proofs"


[[require]]
name = "Lax808846"
git = "https://github.com/lax-archive/lax-submissions"
rev = "9394e531cc51cb67a0214bca3f9264dfe97ba5c7"
subDir = "word-ram/concepts"

[[require]]
name = "Lax759944Proofs"
git = "https://github.com/szymtor/RAM-TM"
rev = "134e398cef46599371df99f10c9007bc34ba3868"
subDir = "proofs"
